#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(theme = shinytheme("slate"),
            fluidRow(
                # Application title
                titlePanel("Data Explorer")),        
            fluidRow(
                column(2,
                       wellPanel(selectInput("boundary", "Boundary:",
                                             choices = c("Custom" = "Custom",
                                                         "Zip" = "zip",
                                                         "City" = "city")),
                                 selectizeInput("city", "City:", city$NAME10, multiple = TRUE),
                                 selectizeInput("zip", "Zip Code:", zip$ZCTA5CE10, multiple = TRUE),
                                 selectInput("map_variable", "Map Variable", 
                                             choices = c("Year Built" = "year_built", 
                                                         "Close Price" = "close_price", 
                                                         "Year Sold" = "year_sold", 
                                                         "Property Type" = "property_type",
                                                         "Style" = "architecture_style",
                                                         "Material" = "construction_material",
                                                         "DOM" = "days_on_market",
                                                         "List Price" = "list_price",
                                                         "Price per Sqft" = "psf_total",
                                                         "Close Price to List Price" = "close_to_original_list_price",
                                                         "Beds" = "beds",
                                                         "Baths" = "baths",
                                                         "Property Condition" = "property_condition",
                                                         "Prop Sqft" = "total_sqft",
                                                         "DOM Bin" ="dom_bucket",
                                                         "Year Built Decade" = "year_built_decade")),
                                 selectInput("color_type", "Variable Coloring Scheme:",
                                             choices = c("Range" = "range",
                                                         "Quantile" = "quantile",
                                                         "Bin" = "bin")),
                                 selectInput("prop_type", "Property Type:",
                                             choices = c("Single Family Residence", 
                                                         "Condominium",
                                                         "Multi-Family",
                                                         "Townhouse", "Deeded Parking",
                                                         "New Home Plan", "New Home Community",
                                                         "Duplex", "Apartment", "Triplex"),
                                             multiple = TRUE),
                                 numericRangeInput("beds", "Beds", value = c(0, 10)),
                                 numericRangeInput("baths", "Baths", value = c(0, 10)),
                                 numericRangeInput("lot_size", "Lot Size (SqFt)", value = c(0, 10000)),
                                 numericRangeInput("prop_size", "Property  Size (SqFt)", value = c(0, 10000)),
                                 numericRangeInput("year_built", "Year Built", value = c(0, 2020)),
                                 sliderInput("year_sold", "Year Sold:", min = 2008,
                                             max = 2020, 
                                             value = c(2008, 2020), 
                                             sep = ""),
                                 sliderInput("month_sold", "Month Sold:", min = 1,
                                             max = 12, 
                                             value = c(1, 12), 
                                             sep = ""),
                                 sliderInput("close_price", "close Price:", min = 0,
                                             max = 2000000, value = c(0, 2000000),
                                             sep = ",", pre = "$", 
                                             round = 3, 
                                             step = 1000))),
                column(2,
                       wellPanel(selectInput("graph_type_1v", "Graph Type:",
                                             choices = c("Bar" = "bar", 
                                                         "Box Plot" = "box_plot", 
                                                         "Density" = "density")),
                                 conditionalPanel("input.graph_type_1v == 'bar'",
                                                  selectInput("x_axis_bar", "X-Axis:", 
                                                              choices = c("Year Sold" = "year_sold",
                                                                          "Year Built" = "year_built",
                                                                          "Property Type" = "property_type",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Zoning" = "zoning",
                                                                          "Year Buildt Decade" = "year_built_decade",
                                                                          "DOM Bin" = "dom_bucket",
                                                                          "Property Condition" = "property_condition",
                                                                          "Month Sold" = "month_sold")),
                                                  selectInput("bar_color", "Color:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Property Type" = "property_type",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Zoning" = "zoning",
                                                                          "DOM Bin" = "dom_bucket",
                                                                          "Year Built Decade" = "year_built_decade")),
                                                  selectInput("bar_facet", "Facet Variable:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Property Type" = "property_type",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Zoning" = "zoning",
                                                                          "Basement Y/N" = "basement_flag",
                                                                          "DOM Bin" = "dom_bucket",
                                                                          "Year Built Decade" = "year_built_decade"))),
                                 conditionalPanel("input.graph_type_1v == 'box_plot'",
                                                  selectInput("x_axis_box", "X-Axis:", 
                                                              choices = c("Year Sold" = "year_sold",
                                                                          "Year Built" = "year_built",
                                                                          "Close Price" = "close_price",
                                                                          "Beds" = "beds", 
                                                                          "Baths" = "baths",
                                                                          "Price per SqFt" = "psf_total",
                                                                          "Close to List Price" = "close_to_list_price",
                                                                          "Lot Size SqFt" = "lot_size_sqft",
                                                                          "DOM" = "days_on_market",
                                                                          "Close Price to Original List Price" = 
                                                                            "close_to_original_list_price",
                                                                          "Total SqFt" = "total_sqft"))),
                                 conditionalPanel("input.graph_type_1v == 'density'",
                                                  selectInput("x_axis_density", "X-Axis:", 
                                                              choices = c("Year Sold" = "year_sold",
                                                                          "Year Built" = "year_built",
                                                                          "Close Price" = "close_price",
                                                                          "Beds" = "beds", 
                                                                          "Baths" = "baths",
                                                                          "Price per SqFt" = "psf_total",
                                                                          "Close to Original List Price" = 
                                                                            "close_to_original_list_price",
                                                                          "Lot Size SqFt" = "lot_size_sqft",
                                                                          "Total SqFt" = "total_sqft")),
                                                  selectInput("density_color", "Color:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Property Type" = "property_type",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Zoning" = "zoning",
                                                                          "DOM Bin" = "dom_bucket",
                                                                          "Year Built Decade" = "year_built_decade",
                                                                          "Basement Y/N" = "basement_flag")),
                                                  selectInput("density_facet", "Facet Variable:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Property Type" = "property_type",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Zoning" = "zoning",
                                                                          "Basement Y/N" = "basement_flag",
                                                                          "DOM Bin" = "dom_bucket",
                                                                          "Year Built Decade" = "year_built_decade")))),
                       wellPanel(selectInput("graph_type_2v", "Graph Type:",
                                             choices = c("Scatter" = "scatter",
                                                         "Bar" = "bar", 
                                                         "Box Plot" = "box_plot",
                                                         "Line" = "line")),
                                 conditionalPanel("input.graph_type_2v == 'scatter'",
                                                  selectInput("x_axis_2v_scatter", "X-Axis:",
                                                              choices = c("Year Built" = "year_built",
                                                                          "Year Sold" = "year_sold",
                                                                          "DOM" = "days_on_market",
                                                                          "Total SqFt" = "total_sqft",
                                                                          "Lot Size" = "lot_size_sqft",
                                                                          "Beds" = "beds",
                                                                          "Baths" = "baths",
                                                                          "List Price" = "list_price",
                                                                          "Close Price to Original List Price" = 
                                                                            "close_price_to_original_list_price",
                                                                          "Price per SqFt" = "psf_total")),
                                                  selectInput("y_axis_2v_scatter", "Y-Axis:", 
                                                              choices = c("Close Price" = "close_price",
                                                                          "DOM" = "days_on_market",
                                                                          "Total SqFt" = "total_sqft",
                                                                          "Lot Size" = "lot_size_sqft",
                                                                          "Original List Price" = "original_list_price",
                                                                          "Price per SqFt" = "psf_total")),
                                                  selectInput("scatter_color", "Color:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Close Price" = "close_price",
                                                                          "DOM" = "days_on_market",
                                                                          "Total SqFt" = "total_sqft",
                                                                          "Property Condition" = "property_condition",
                                                                          "Style" = "architecture_style",
                                                                          "Year Built" = "year_built",
                                                                          "Beds" = "beds",
                                                                          "Baths" = "baths",
                                                                          "Lot Size" = "lot_size_sqft",
                                                                          "Material" = "construction_material",
                                                                          "Basement Y/N" = "basement_flag",
                                                                          "DOM Bin" = "dom_bucket", 
                                                                          "Year Built Decade" = "year_built_decade",
                                                                          "Close to Original List Price" = 
                                                                            "close_to_original_list_price",
                                                                          "Price per Sqft" = "psf_total")),
                                                  selectInput("scatter_size", "Size:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Close Price" = "close_price",
                                                                          "DOM" = "days_on_market",
                                                                          "Total SqFt" = "total_sqft",
                                                                          "Property Condition" = "property_condition",
                                                                          "Style" = "architecture_style",
                                                                          "Year Built" = "year_built",
                                                                          "Beds" = "beds",
                                                                          "Baths" = "baths",
                                                                          "Lot Size" = "lot_size_sqft",
                                                                          "Material" = "construction_material",
                                                                          "Basement Y/N" = "basement_flag")),
                                                  selectInput("scatter_shape", "Shape:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Close Price" = "close_price",
                                                                          "DOM" = "days_on_market",
                                                                          "Total SqFt" = "total_sqft",
                                                                          "Property Condition" = "property_condition",
                                                                          "Style" = "architecture_style",
                                                                          "Year Built" = "year_built",
                                                                          "Beds" = "beds",
                                                                          "Baths" = "baths",
                                                                          "Lot Size" = "lot_size_sqft",
                                                                          "Material" = "construction_material",
                                                                          "Basement Y/N" = "basement_flag")),
                                                  selectInput("scatter_facet", "Facet Variable:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Property Condition" = "property_condition",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Basement Y/N" = "basement_flag"))),
                                 conditionalPanel("input.graph_type_2v == 'bar'",
                                                  selectInput("x_axis_2v_bar", "X-Axis:",
                                                              choices = c("Year Built" = "year_built",
                                                                          "Year Sold" = "year_sold",
                                                                          "Zoning" = "zoning",
                                                                          "Property Type" = "property_type",
                                                                          "Property Condition" = "property_condition")),
                                                  selectInput("color_bar", "Facet Variable:", 
                                                              choices = c("Nothing" = "",
                                                                          "Property Type" = "property_type",
                                                                          "Zoning" = "zoning",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Basement Type" = "basement_type",
                                                                          "Property Condition" = "property_condition"))),
                                 conditionalPanel("input.graph_type_2v == 'box_plot'",
                                                  selectInput("x_axis_2v_box", "X-Axis:",
                                                              choices = c("Year Built" = "year_built",
                                                                          "Year Sold" = "year_sold",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Basement Y/N" = "basement_flag",
                                                                          "Property Type" = "property_type",
                                                                          "Property Condition" = "property_condition")),
                                                  selectInput("y_axis_2v_box", "Y-Axis:", 
                                                              choices = c("Close Price" = "close_price",
                                                                          "DOM" = "days_on_market",
                                                                          "Total SqFt" = "total_sqft"))),
                                 conditionalPanel("input.graph_type_2v == 'line'",
                                                  selectInput("x_axis_2v_line", "X-Axis:",
                                                              choices = c("Year Sold" = "year_sold",
                                                                          "Total SqFt" = "total_sqft",
                                                                          "Lot Size" = "lot_size_sqft")),
                                                  selectInput("y_axis_2v_line", "Y-Axis:", 
                                                              choices = c("Close Price" = "close_price",
                                                                          "DOM" = "days_on_market")),
                                                  selectInput("line_color", "Color:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Property Type" = "property_type",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Zoning" = "zoning")),
                                                  selectInput("line_facet", "Facet Variable:", 
                                                              choices = c("Nothing" = "Nothing",
                                                                          "Property Type" = "property_type",
                                                                          "Style" = "architecture_style",
                                                                          "Material" = "construction_material",
                                                                          "Zoning" = "zoning",
                                                                          "Basement Y/N" = "basement_flag"))))),
                column(8,
                  fluidRow(
                    wellPanel(leafletOutput("mymap", height = "750px")))),
                  fluidRow(
                    column(1,
                           wellPanel(
                             h4("Number Sold:"),
                             h4(textOutput("num_sold"))
                           )),
                    column(1,
                           wellPanel(
                             h4("Median Sold Price:"),
                             h4(textOutput("med_close_price"))
                           )),
                    column(1,
                           wellPanel(
                             h4("Mean Sold Price:"),
                             h4(textOutput("mean_close_price"))
                           )))
        ),
            fluidRow(
                column(6,
                    plotOutput("graph_1v", height = 750)),
                column(6,
                    plotOutput("graph_2v", height = 750))
                # column(4,  
                #   fluidRow(
                #     column(4,
                #          wellPanel(
                #            h4("Number Sold:"),
                #            h4(textOutput("num_sold"))
                #          ))),
                #   fluidRow(
                #     column(4, 
                #           wellPanel(
                #             h4("Median Sold Price:"),
                #             h4(textOutput("med_close_price"))
                #          )),
                #     column(4,
                #           wellPanel(
                #             h4("Mean Sold Price:"),
                #             h4(textOutput("mean_close_price"))
                #           ))),
                #   fluidRow(
                #     column(4, 
                #            wellPanel())
                #   )
        ),
            fluidRow(
                column(12,
                    wellPanel(tableOutput("my_df")))
            )
                
    )
)


    